apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sorting-viz
  namespace: sorting-viz
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/upgrade: websocket
    nginx.ingress.kubernetes.io/connection: Upgrade
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /experiments
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
